name: 'SCP deploy action'
description: 'Copy files to remote server'
author: 'Andy Schneider'
inputs:
  host:
    description: 'SSH hostname'
    required: true
  user:
    description: 'SSH User name'
    required: true
  key:
    description: 'Private key'
    required: true
  from:
    description: 'From'
    required: true
  to:
    description: 'To'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'